apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: node-express
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
  labels:
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: node-express
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: node-express
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: node-express
    spec:
      containers:
      - image: eu.gcr.io/tap-shared-instance/workloads/node-express-dev@sha256:9415ab4e84b40e4e14fcfd46589d4fd260b0c76b96e048464f15c8ef3d58ef99
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

